CREATE DATABASE  ControlIncidenciasDB
GO
USE ControlIncidenciasDB
GO

CREATE TABLE EDIFICIO(
	 ID INT IDENTITY,
	 Nombre NVARCHAR(30) NOT NULL, 
	 Ubicacion NVARCHAR(1000) NOT NULL,
	 ID_Depto INT
)
GO
CREATE TABLE LOCALIZACION( 
	 ID INT IDENTITY,
	 Nombre NVARCHAR(100) NOT NULL,
	 NumPlanta INT,
	 ID_Edificio INT,
	 Ubicacion NVARCHAR(1000) NOT NULL
)
GO
CREATE TABLE DEPARTAMENTO(
	ID INT IDENTITY,
	Nombre NVARCHAR(30) NOT NULL,
	ID_EmpEncar INT,
	Estatus BIT -- 0 INACTIVO / 1 ACTIVO --
)
GO
CREATE TABLE EMPLEADO(
	ID INT IDENTITY,
	Nombre NVARCHAR(350) NOT NULL,
	Email NVARCHAR(35) NOT NULL,
	Celular NVARCHAR(12) NOT NULL,
	Direccion NVARCHAR(350) NOT NULL,
	ID_Rol INT,
	Contraseña NVARCHAR(20) NOT NULL,
	Estatus BIT -- 0 INACTIVO / 1 ACTIVO --
)
GO
CREATE TABLE EMPLEADO_DEPTO(
	ID_Empleado INT,
	ID_Depto INT
)
GO
CREATE TABLE ROL(
	ID INT IDENTITY,
	Nombre NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE PROVEEDOR(
	ID INT IDENTITY,
	Nombre NVARCHAR(500) NOT NULL,
	RFC NVARCHAR(13) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	Telefono NVARCHAR(12) NOT NULL,
	Direccion NVARCHAR(800) NOT NULL
)
GO
CREATE TABLE CI(
	ID INT IDENTITY,
	Nombre NVARCHAR(500) NOT NULL,
	Descripcion NVARCHAR(4000) NOT NULL,
	NumSerie NVARCHAR(30) NOT NULL,
	FechaAdquisicion DATE NOT NULL,
	ID_Localizacion INT,
	ID_Encargado INT,
	ID_Proveedor INT,
	Estatus BIT -- 0 INACTIVO / 1 ACTIVO --
)
GO
CREATE TABLE INCIDENCIA(
	ID INT IDENTITY,
	Descripcion NVARCHAR(1000) NOT NULL,
	FechaInicio DATE,
	FechaTerminacion DATE,
	ID_Prioridad INT,
	ID_CI INT,
	ID_Tecnico INT,
	ID_Stat INT,
	ID_Tipo INT,
	Califiacion NVARCHAR(50),
	Comentario NVARCHAR(1000),
	Ubicacion NVARCHAR(1000),
	Tiempo_Respuesta NVARCHAR(50),
	ID_Usuario INT NOT NULL
)
GO
CREATE TABLE PRIORIDAD(
	ID INT IDENTITY,
	Descripcion NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE ESTATUS_INCIDENCIA(
	ID INT IDENTITY,
	Descripcion NVARCHAR(15) NOT NULL
)
GO
CREATE TABLE TIPO_INCIDENCIA(
	ID INT IDENTITY,
	Descripcion NVARCHAR(15) NOT NULL
)
GO
CREATE TABLE PROBLEMAS_CONOCIDOS(
	ID INT IDENTITY,
	Descripcion NVARCHAR(2000) NOT NULL,
	Solucion NVARCHAR(3500) NOT NULL,
	Tiempo NVARCHAR(30) NOT NULL
)
GO
CREATE TABLE CAMBIOS_CI(
	ID INT IDENTITY,
	IDCI INT,
	Nombre NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(4000) NOT NULL,
	NumSerie NVARCHAR(30) NOT NULL,
	FechaAdquisicion DATE NOT NULL,
	ID_Localizacion INT,
	ID_Encargado INT,
	ID_Proveedor INT,
	Estatus BIT, -- 0 INACTIVO / 1 ACTIVO --
)
GO
CREATE TABLE CAMBIOS(
	ID INT IDENTITY,
	IDInc INT,
	Descripcion NVARCHAR(1500) NOT NULL,
	Comentario NVARCHAR(1000),
	FechaSol DATE NOT NULL,
	FechaTer DATE,
	Estatus INT NOT NULL
)
GO
CREATE TABLE ESTATUS_CAMBIO(
	ID INT IDENTITY,
	Descripcion NVARCHAR(15) NOT NULL
)
GO
---------------------------------------- PRIMARY KEYS ----------------------------------------

ALTER TABLE EDIFICIO
ADD CONSTRAINT PK_Edificio PRIMARY KEY(ID)

ALTER TABLE LOCALIZACION
ADD CONSTRAINT PK_Localizacion PRIMARY KEY(ID)

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PK_Departamento PRIMARY KEY(ID)

ALTER TABLE EMPLEADO
ADD CONSTRAINT PK_Empleado PRIMARY KEY(ID)

ALTER TABLE ROL
ADD CONSTRAINT PK_Rol PRIMARY KEY(ID)

ALTER TABLE PROVEEDOR
ADD CONSTRAINT PK_Proveedor PRIMARY KEY(ID)

ALTER TABLE CI
ADD CONSTRAINT PK_CI PRIMARY KEY(ID)

ALTER TABLE ESTATUS_INCIDENCIA
ADD CONSTRAINT PK_EstatusIncidencia PRIMARY KEY(ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT PK_Incidencia PRIMARY KEY(ID)

ALTER TABLE TIPO_INCIDENCIA
ADD CONSTRAINT PK_TipoIncidencia PRIMARY KEY(ID)

ALTER TABLE PROBLEMAS_CONOCIDOS
ADD CONSTRAINT PK_Problemas_conocidos PRIMARY KEY(ID)

ALTER TABLE CAMBIOS_CI
ADD CONSTRAINT PK_Cambios_CI PRIMARY KEY (ID)

ALTER TABLE CAMBIOS
ADD CONSTRAINT PK_Cambios PRIMARY KEY (ID)

GO

---------------------------------------- FOREIGN KEYS ----------------------------------------

ALTER TABLE EDIFICIO
ADD CONSTRAINT FK_Edificio_Depto FOREIGN KEY(ID_Depto) REFERENCES DEPARTAMENTO (ID)

ALTER TABLE LOCALIZACION
ADD CONSTRAINT FK_Localizacion_Edificio FOREIGN KEY(ID_Edificio) REFERENCES EDIFICIO (ID)

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT FK_Encargado_Depto FOREIGN KEY(ID_EmpEncar) REFERENCES EMPLEADO (ID)

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_Empleado_Rol FOREIGN KEY(ID_Rol) REFERENCES ROL (ID)

ALTER TABLE EMPLEADO_DEPTO
ADD CONSTRAINT FK_EmpleadoDepto_Empleado FOREIGN KEY(ID_Empleado) REFERENCES EMPLEADO (ID)

ALTER TABLE EMPLEADO_DEPTO
ADD CONSTRAINT FK_EmpleadoDepto_Depto FOREIGN KEY(ID_Depto) REFERENCES DEPARTAMENTO (ID)

ALTER TABLE CI
ADD CONSTRAINT FK_CI_Localizacion FOREIGN KEY(ID_Localizacion) REFERENCES LOCALIZACION (ID)

ALTER TABLE CI
ADD CONSTRAINT FK_CI_Encargado FOREIGN KEY(ID_Encargado) REFERENCES EMPLEADO (ID)

ALTER TABLE CI
ADD CONSTRAINT FK_CI_Provedor FOREIGN KEY(ID_Proveedor) REFERENCES PROVEEDOR (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Indcidencia_CI FOREIGN KEY(ID_CI) REFERENCES CI (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Indcidencia_Tecnico FOREIGN KEY(ID_Tecnico) REFERENCES EMPLEADO (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Incidencia_Estatus FOREIGN KEY(ID_Stat) REFERENCES ESTATUS_INCIDENCIA (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Incidencia_Tipo FOREIGN KEY(ID_Tipo) REFERENCES TIPO_INCIDENCIA (ID)

ALTER TABLE INCIDENCIA
ADD CONSTRAINT FK_Incidencia_Usuario FOREIGN KEY(ID_Usuario) REFERENCES EMPLEADO (ID)
GO

---------------------------------------- TRIGGERS ----------------------------------------
CREATE TRIGGER TG_UPDATE_CI ON CI FOR UPDATE
AS
	DECLARE @IDCI INT
	DECLARE @Name NVARCHAR(50)
	DECLARE @Desc NVARCHAR(4000)
	DECLARE @NumSerie NVARCHAR(40)
	DECLARE @FechaAd DATE
	DECLARE @LocID INT
	DECLARE @EncID INT
	DECLARE @ProID INT
	DECLARE @Est BIT

	SELECT @IDCI=ID,@Name=Nombre,@Desc=Descripcion,@NumSerie=NumSerie,@FechaAd=FechaAdquisicion,@LocID=ID_Localizacion,@EncID=ID_Encargado,@ProID=ID_Proveedor,@Est=Estatus FROM inserted 
	
	IF UPDATE(ID_Encargado)
		BEGIN
			INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus) 
			VALUES(@IDCI,@Name,@Desc,@NumSerie,@FechaAd,@LocID,@EncID,@ProID,@Est) 
		END
	IF UPDATE(Estatus)
		BEGIN
			INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus) 
			VALUES(@IDCI,@Name,@Desc,@NumSerie,@FechaAd,@LocID,@EncID,@ProID,@Est) 
		END
GO
---------------------------------------- POBLACION ----------------------------------------
INSERT INTO ROL(Nombre) 
VALUES ('ADMINISTRADOR') 
INSERT INTO ROL (Nombre) 
VALUES ('JEFE DE TALLER') 
INSERT INTO ROL (Nombre) 
VALUES ('TECNICO') 
INSERT INTO ROL (Nombre) 
VALUES ('DOCENTE') 
SELECT * FROM ROL

INSERT INTO PRIORIDAD(Descripcion)
VALUES('ALTA')
INSERT INTO PRIORIDAD(Descripcion)
VALUES('MEDIA')
INSERT INTO PRIORIDAD(Descripcion)
VALUES('BAJA')
SELECT * FROM PRIORIDAD

INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('RESUELTA')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('POR CHECAR')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('ACEPTADA')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('EN PROCESO')
INSERT INTO ESTATUS_INCIDENCIA(Descripcion)
VALUES('RECHAZADA')
SELECT * FROM ESTATUS_INCIDENCIA

INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol,Contraseña,Estatus)
VALUES('MARCO ANTONIO RODRIGUEZ AVILES','Marco@itculiacan.edu.mx','6671234567','Villa Alegria',1,'12345',1)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol,Contraseña,Estatus)
VALUES('JORGE GUILLERMO MOYA PALAZUELOS','Jorge@itculiacan.edu.mx','6672567032','Los Cascaveles',2,'12345',1)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol,Contraseña,Estatus)
VALUES('NOEL GARCIA INZUNZA','Noel@itculiacan.edu.mx','6670987654','Rancho Contento',3,'12345',1)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol,Contraseña,Estatus)
VALUES('ELIZABETH BARRAZA GARCIA','Elizabeth@itculiacan.edu.mx','6610293845','Los Pinos',4,'12345',1)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol,Contraseña,Estatus)
VALUES('MARIA DEL ROSARIO GONZALEZ ALVAREZ','Rosario@itculiacan.edu.mx','6610200826','Las lomas',4,'12345',1)
INSERT INTO  EMPLEADO(Nombre,Email,Celular,Direccion,ID_Rol,Contraseña,Estatus)
VALUES('JUAN LOPEZ PEREZ','Juan@itculiacan.edu.mx','6670937524','Aguaruto',3,'12345',1)
SELECT * FROM EMPLEADO 

INSERT INTO DEPARTAMENTO(Nombre,ID_EmpEncar,Estatus)
VALUES('SISTEMAS',1,1)
INSERT INTO DEPARTAMENTO(Nombre,ID_EmpEncar,Estatus)
VALUES('CIENCIAS BASICAS',4,1)
INSERT INTO DEPARTAMENTO(Nombre,ID_EmpEncar,Estatus)
VALUES('FINANZAS',5,1)
SELECT * FROM DEPARTAMENTO

INSERT INTO EDIFICIO(Nombre,Ubicacion,ID_Depto)
VALUES('A','CERCA DE LA ENTRADA PRINCIPAL AUN LADO DEL ESTANQUE',1)
INSERT INTO EDIFICIO(Nombre,Ubicacion,ID_Depto)
VALUES('B','SEGUNDO EDIFICIO DESPUES DE ENTRAR POR LA PUERTA PRINCIPAL',1)
INSERT INTO EDIFICIO(Nombre,Ubicacion,ID_Depto)
VALUES('UP','EDIFICIO QUE ESTA ATRAS DEL SEGUNDO ESTACIONAMIENTO, DE COLOR LILA',1)
SELECT * FROM EDIFICIO

INSERT INTO LOCALIZACION(Nombre,NumPlanta,ID_Edificio,Ubicacion)
VALUES('CUBICULO 4',1,1,'DENTRO DEL EDIFICIO GIRAR A LA IZQUIERDA Y CAMINAR HASTA EL FONDO')
INSERT INTO LOCALIZACION(Nombre,NumPlanta,ID_Edificio,Ubicacion)
VALUES('SALON S19',1,2,'POR LA PARTE TRASERA DEL EDIFICIO, DEL LADO DERECHO CAMINAR HASTA EL FONO')
SELECT * FROM LOCALIZACION

INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(1,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(2,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(3,1)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(4,2)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(5,3)
INSERT INTO EMPLEADO_DEPTO(ID_Empleado,ID_Depto)
VALUES(6,1)
SELECT * FROM EMPLEADO_DEPTO

INSERT INTO PROVEEDOR(Nombre,RFC,Email,Telefono,Direccion)
VALUES('VISION COMPUTERS','ABCDFG9871BQ','Vision@computer.mx','6677172032','Río Suchiate, Los Pinos 80128')
INSERT INTO PROVEEDOR(Nombre,RFC,Email,Telefono,Direccion)
VALUES('MICROSOFT','LAERGU6542AP','Microsoft@team.mx','6657184740','Albuquerque, Nuevo México')
INSERT INTO PROVEEDOR(Nombre,RFC,Email,Telefono,Direccion)
VALUES('HP','ABCDEF6542AX','HP@team.mx','6671874095','Prolongacion Paseo de la Reforma Col 700 Del, Álvaro Obregón, 01210 Ciudad de México')
INSERT INTO PROVEEDOR(Nombre,RFC,Email,Telefono,Direccion)
VALUES('CISCO','EF6ABCA54XD2','Cisco@team.mx','6608907495','Paseo de los Tamarindos 400A, Bosques de las Lomas, Cuajimalpa de Morelos, 05120')

SELECT * FROM PROVEEDOR

INSERT INTO CI(Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES('COMPUTADORA HP','MODELO Z8M58LT, COLOR NEGRA, 8 GB DE RAM, PROCESADOR APU AMD A4-9125 CON VELOCIDAD 3.2 GHZ, PROCESADOR PENTIUM SILVER J5040, CAPACIDAD DEL DISCO DURO 1 TB, SISTEMA OPERATIVO WINDOWS 10 DE  64 BITS, CON BLUETOOTH, CUENTA CON LOS PAQUETE DE; OFFICE, SQL, VISUAL STUDIO, TEAMS, JAVA, C#, COREL DRAW, C++, PACKET TRACER, ESTA CONECTADA A LA RED PURO SINALOA PUERTO 120 INTERFAZ DE RED LAN 10/100/1000 GBE INTEGRADA, PANTALLA LED DE 21.5 PULGADAS RESOLUCIÓN DE 1600 X 900 MODELO VISUMLQ, TECLADO OTEPX1, MOUSE IMALQ1, GARANTIA DE 2 AÑOS','12345678','2021/03/16',1,4,3,1)
INSERT INTO CI(Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES('COMPUTADORA MICROSOFT','MODELO AQO30HA, COLOR NEGRA, 4 GB DE RAM, PROCESADOR APU AMD A4-9125 CON VELOCIDAD 3.2 GHZ, PROCESADOR PENTIUM SILVER J5040, CAPACIDAD DEL DISCO DURO 1 TB, SISTEMA OPERATIVO WINDOWS 10 DE  64 BITS, SIN BLUETOOTH, CUENTA CON LOS PAQUETE DE; OFFICE, SQL, VISUAL STUDIO, TEAMS, JAVA, C#, COREL DRAW, C++, PACKET TRACER, ESTA CONECTADA A LA RED PURO SINALOA PUERTO 120 INTERFAZ DE RED LAN 10/100/1000 GBE INTEGRADA, PANTALLA LED DE 21.5 PULGADAS RESOLUCIÓN DE 1600 X 900 MODELO VISUMLQ, TECLADO OTEPX1, MOUSE IMALQ1, GARANTIA DE 3 AÑOS','72834516','2021/03/16',2,5,2,1) 
INSERT INTO CI(Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES('IMPRESORA EPSON','MODELO QKLA190, COLOR NEGRA, VELOCIDAD DE 10 PPM, CARTUCHO DE TINTA EPSRON P10 NEGRA O DE COLORES PAINT DE 80 ML, LA BANDEJA DE ENTRADA RECIBE HASTA 50 HOJAS Y CUENTA CON CONECTIVIDAD WI-FI Y USB','02007541','2021/03/20',1,5,1,1) 
INSERT INTO CI(Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES('TELEFONO VTECH','MODELO CS5119, COLOR NEGRO, TELFONO INALAMBRICO CON IDENTIFICADOR DE LLAMADAS, ALTAVOZ Y MEMORIA PARA AGENDAR 30 CONTACTOS, CUENTA CON 1 AÑO DE GARANTIA','25397190','2021/03/10',1,5,1,1)
INSERT INTO CI(Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES('IMPRESORA HP','MODELO DESKJET IA 2775, COLOR BLANCA, VELOCIDAD DE 7.5 PPM. CARTUCHO DE TINTA HP 711 NEGRA O DE COLORES DESIGNJET ORIGINAL DE 80 ML, LA BANDEJA DE ENTRADA RECIBE HASTA 60 HOJAS Y CUENTA CON CONECTIVIDAD WI-FI Y USB','87654321','2021/03/20',2,4,3,1) 
INSERT INTO CI(Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES('TELEFONO VTECH','MODELO CS5119, COLOR GRIS, TELFONO INALAMBRICO CON IDENTIFICADOR DE LLAMADAS, ALTAVOZ Y MEMORIA PARA AGENDAR 30 CONTACTOS, CUENTA CON 1 AÑO DE GARANTIA','72539192','2021/03/10',2,4,1,1)
SELECT * FROM CI

INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES(1,'COMPUTADORA HP','MODELO Z8M58LT, COLOR NEGRA, 8 GB DE RAM, PROCESADOR APU AMD A4-9125 CON VELOCIDAD 3.2 GHZ, PROCESADOR PENTIUM SILVER J5040, CAPACIDAD DEL DISCO DURO 1 TB, SISTEMA OPERATIVO WINDOWS 10 DE  64 BITS, CON BLUETOOTH, CUENTA CON LOS PAQUETE DE; OFFICE, SQL, VISUAL STUDIO, TEAMS, JAVA, C#, COREL DRAW, C++, PACKET TRACER, ESTA CONECTADA A LA RED PURO SINALOA PUERTO 120 INTERFAZ DE RED LAN 10/100/1000 GBE INTEGRADA, PANTALLA LED DE 21.5 PULGADAS RESOLUCIÓN DE 1600 X 900 MODELO VISUMLQ, TECLADO OTEPX1, MOUSE IMALQ1, GARANTIA DE 2 AÑOS','12345678','2021/03/16',1,4,3,1)
INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES(2,'COMPUTADORA MICROSOFT','MODELO AQO30HA, COLOR NEGRA, 4 GB DE RAM, PROCESADOR APU AMD A4-9125 CON VELOCIDAD 3.2 GHZ, PROCESADOR PENTIUM SILVER J5040, CAPACIDAD DEL DISCO DURO 1 TB, SISTEMA OPERATIVO WINDOWS 10 DE  64 BITS, SIN BLUETOOTH, CUENTA CON LOS PAQUETE DE; OFFICE, SQL, VISUAL STUDIO, TEAMS, JAVA, C#, COREL DRAW, C++, PACKET TRACER, ESTA CONECTADA A LA RED PURO SINALOA PUERTO 120 INTERFAZ DE RED LAN 10/100/1000 GBE INTEGRADA, PANTALLA LED DE 21.5 PULGADAS RESOLUCIÓN DE 1600 X 900 MODELO VISUMLQ, TECLADO OTEPX1, MOUSE IMALQ1, GARANTIA DE 3 AÑOS','72834516','2021/03/16',2,5,2,1) 
INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES(3,'IMPRESORA EPSON','MODELO QKLA190, COLOR NEGRA, VELOCIDAD DE 10 PPM, CARTUCHO DE TINTA EPSRON P10 NEGRA O DE COLORES PAINT DE 80 ML, LA BANDEJA DE ENTRADA RECIBE HASTA 50 HOJAS Y CUENTA CON CONECTIVIDAD WI-FI, USB Y 2 AÑOS DE GARANTIA','02007541','2021/03/20',1,5,1,1) 
INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES(4,'TELEFONO VTECH','MODELO CS5119, COLOR NEGRO, TELFONO INALAMBRICO CON IDENTIFICADOR DE LLAMADAS, ALTAVOZ Y MEMORIA PARA AGENDAR 30 CONTACTOS, CUENTA CON 1 AÑO DE GARANTIA','25397190','2021/03/10',1,5,1,1)
INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES(5,'IMPRESORA HP','MODELO DESKJET IA 2775, COLOR BLANCA, VELOCIDAD DE 7.5 PPM. CARTUCHO DE TINTA HP 711 NEGRA O DE COLORES DESIGNJET ORIGINAL DE 80 ML, LA BANDEJA DE ENTRADA RECIBE HASTA 60 HOJAS Y CUENTA CON CONECTIVIDAD WI-FI, USB Y 2 AÑOS DE GARANTIA','87654321','2021/03/20',2,4,3,1) 
INSERT INTO CAMBIOS_CI(IDCI,Nombre,Descripcion,NumSerie,FechaAdquisicion,ID_Localizacion,ID_Encargado,ID_Proveedor,Estatus)
VALUES(6,'TELEFONO VTECH','MODELO CS5119, COLOR GRIS, TELFONO INALAMBRICO CON IDENTIFICADOR DE LLAMADAS, ALTAVOZ Y MEMORIA PARA AGENDAR 30 CONTACTOS, CUENTA CON 1 AÑO DE GARANTIA','72539192','2021/03/10',2,4,1,1)
SELECT * FROM CAMBIOS_CI

INSERT INTO TIPO_INCIDENCIA(Descripcion)
VALUES('CI')
INSERT INTO TIPO_INCIDENCIA(Descripcion)
VALUES('RED')
INSERT INTO TIPO_INCIDENCIA(Descripcion)
VALUES('SOFTWARE')
SELECT * FROM TIPO_INCIDENCIA

INSERT INTO ESTATUS_CAMBIO(Descripcion)
VALUES('POR ATENDER')
INSERT INTO ESTATUS_CAMBIO(Descripcion)
VALUES('APROBADA')
INSERT INTO ESTATUS_CAMBIO(Descripcion)
VALUES('RECHAZADA')
SELECT * FROM ESTATUS_CAMBIO

INSERT INTO PROBLEMAS_CONOCIDOS(Descripcion,Solucion,Tiempo)
VALUES('RESTABLECER WINDOWS 10 A SU ESTADO ORIGINAL SIN PERDER ARCHIVOS Y CONFIGURACIÓN','ABRIR EL PANEL DE CONFIGURACIÓN. LUEGO HAZ CLICK EN ACTUALIZACIÓN Y SEGURIDAD > RECUPERACIÓN > RESTABLECER ESTE PC > COMENZAR. UNA VEZ PRESIONADO EL BOTÓN PARA COMENZAR APARECERÁ UNA VENTANA EMERGENTE QUE TE DARÁ DOS OPCIONES DIFERENTES PARA RESTABLECER TU EQUIPO. LA PRIMERA TE DEJA MANTENER ARCHIVOS, Y LA SEGUNDA DICE QUITAR TODO. PARA ESTO DEVERAS SELECCIONAR LA PRIMERA OPCIÓN, ESTA VA A REINSTALAR WINDOWS 10 MANTENIENDO TUS ARCHIVOS PERSONALES. VA A QUITAR LAS APLICACIONES Y CONTROLADORES INSTALADOS, ELIMINARÁ LOS CAMBIOS REALIZADOS EN LA CONFIGURACIÓN','30 MINUTOS')
INSERT INTO PROBLEMAS_CONOCIDOS(Descripcion,Solucion,Tiempo)
VALUES('INSTALAR PAQUETE OFFICE','INGRESE A LA PAGINA OFICIAL DE OFFICE E INICIE SESION CON LA CUENTA ASOCIADA A ESTA VERSIÓN DE OFFICE. DESPUÉS, SIGA LOS PASOS QUE COINCIDAN CON EL TIPO DE CUENTA CON LA CUAL HA INICIADO SESIÓN. SEGÚN EL NAVEGADOR, HAGA CLIC EN EJECUTAR, INSTALAR O GUARDAR ARCHIVO.SI VE EL AVISO DEL CONTROL DE CUENTAS DE USUARIO CON EL MENSAJE ¿QUIERES PERMITIR QUE ESTA APLICACIÓN HAGA CAMBIOS EN EL DISPOSITIVO? HAGA CLIC EN SÍ.SE INICIARÁ LA INSTALACIÓN.LA INSTALACIÓN HABRÁ FINALIZADO CUANDO VEA LA FRASE "YA ESTÁ LISTO. OFFICE ESTÁ INSTALADO" Y SE REPRODUZCA UNA ANIMACIÓN PARA MOSTRARLE EN QUÉ LUGAR DEL EQUIPO PODRÁ ENCONTRAR LAS APLICACIONES DE OFFICE. SELECCIONE CERRAR','10 MINUTOS')
INSERT INTO PROBLEMAS_CONOCIDOS(Descripcion,Solucion,Tiempo)
VALUES('INSTALAR EL PROGRAMA CORELDRAW','IR AL SITIO WEB DE CORELDRAW, Y HACER CLIC EN EL BOTÓN "CORELDRAW GRAPHICS SUITE X4", PARA DESPUES HACER CLIC EN EL BOTÓN DESCARGAR, PARA EMPEZAR LA INSTALACIÓN ABRE EL ARCHIVO QUE DESCARGASTE HACIENDO CLIC EN ÉL UNA VEZ QUE INSTALLSHIELD TERMINE DE DESCARGAR LOS ARCHIVOS NECESARIOS, EL ACUERDO DE LICENCIA SE ABRIRÁ, DEBES LEER LOS TÉRMINOS Y ACEPTAR, DESPUES DEBERAS INGRESA LA INFORMACIÓN DEL USAURIO, DESPUES ELIGE LA CONFIGURACIÓN "CORELDRAW".  PARA TERMINA LA INSTALACIÓN ASEGÚRATE DE NO ABRIR OTROS PROCESOS O PROGRAMAS MIENTRAS QUE ESTÉ EN PROCESO LA INSTALACIÓN PARA PREVENIR ERRORES.','20 MINUTOS')
SELECT * FROM PROBLEMAS_CONOCIDOS

--USE master
--DROP DATABASE ControlIncidenciasDB

